export const GKX_PAGES = [
  'analysis-start.html',
  'analysis-start.raw.html',
  'case-share.html',
  'clustering-results.html',
  'clustering-task.html',
  'common-network.html',
  'common-network-task.html',
  'competition-report.html',
  'data-dashboard.html',
  'data-dashboard-new.html',
  'delphi.html',
  'entity-list.html',
  'frontier-tech.html',
  'home.html',
  'hot-analysis.html',
  'insight-publish.html',
  'media-focus.html',
  'multi-source-data.html',
  'multi-source-data-new.html',
  'multi-source-data.raw2.html',
  'paper-dashboard.html',
  'paper-task.html',
  'patent.html',
  'problem-identification.html',
  'problem-trend.html',
  'project-stats.html',
  'project-task.html',
  'report-gen-ai.html',
  'report-generation.html',
  'shenzhen-list.html',
  'social-network-import.html',
  'social-network-metrics.html',
  'social-network-visualize.html',
  'strategy-cases.html',
  'strategy-shell.html',
  'tech-alert.html',
  'tech-roadmap.html',
  'tech-system.html',
  'tech-trend.html',
] as const

export type GkxPage = (typeof GKX_PAGES)[number]
