#!/usr/bin/env python3
"""Generate src/App.jsx route table from gkx-prototype html pages.

This keeps the router explicit (Boss can audit routes quickly) and avoids
runtime dynamic imports.

Inputs:
- src/pages/prototype/_map.json generated by scripts/gen_prototype_pages.py

Output:
- src/App.jsx
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    rows = json.loads(Path("src/pages/prototype/_map.json").read_text(encoding="utf-8"))

    imports: list[tuple[str, str, str, str]] = []
    strategy_children: list[str] = []
    research_children: list[str] = []

    for system, html_name, base in rows:
        comp_id = f"P_{base}"
        imports.append((comp_id, base, html_name, system))
        child = f"{{ path: '{html_name}', element: <{comp_id} /> }}"
        (research_children if system == "research" else strategy_children).append(child)

    imports.sort(key=lambda x: x[1])
    strategy_children.sort()
    research_children.sort()

    lines: list[str] = []
    lines.append("import { createBrowserRouter, Navigate, Outlet, RouterProvider } from 'react-router-dom'")
    lines.append("")
    lines.append("import Layout from './layouts/Layout.jsx'")
    lines.append("import ResearchLayout from './layouts/ResearchLayout.jsx'")
    lines.append("")
    lines.append("import Home from './pages/Home.jsx'")
    lines.append("import Blank from './pages/Blank.jsx'")
    lines.append("")
    lines.append("// Auto-generated static imports for prototype pages (dangerouslySetInnerHTML).")
    for comp_id, base, html_name, system in imports:
        lines.append(f"import {comp_id} from './pages/prototype/{base}.jsx'")

    lines.append("")
    lines.append("function Root() {")
    lines.append("  return <Outlet />")
    lines.append("}")
    lines.append("")
    lines.append("const router = createBrowserRouter([")
    lines.append("  {")
    lines.append("    path: '/',")
    lines.append("    element: <Root />,")
    lines.append("    children: [")
    lines.append("      { index: true, element: <Navigate to=\"/home\" replace /> },")
    lines.append("      { path: 'home', element: <Home /> },")
    lines.append("")
    lines.append("      {")
    lines.append("        path: 'strategy',")
    lines.append("        element: <Layout />,")
    lines.append("        children: [")
    for c in strategy_children:
        lines.append(f"          {c},")
    lines.append("          { path: ':page', element: <Blank /> },")
    lines.append("        ],")
    lines.append("      },")
    lines.append("")
    lines.append("      {")
    lines.append("        path: 'research',")
    lines.append("        element: <ResearchLayout />,")
    lines.append("        children: [")
    for c in research_children:
        lines.append(f"          {c},")
    lines.append("          { path: ':page', element: <Blank /> },")
    lines.append("        ],")
    lines.append("      },")
    lines.append("")
    lines.append("      { path: '*', element: <Navigate to=\"/home\" replace /> },")
    lines.append("    ],")
    lines.append("  },")
    lines.append("])")
    lines.append("")
    lines.append("export default function App() {")
    lines.append("  return <RouterProvider router={router} />")
    lines.append("}")

    Path("src/App.jsx").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote src/App.jsx with {len(imports)} prototype page imports")


if __name__ == "__main__":
    main()
